# NLP Sept: 2024

In this notebook, we have an end-to-end NLP crash course for september 2024

Authors:
- Eng. Ahmed Métwalli
- Eng. Alia Elhefny

## Section 1: Introduction to Natural Language Processing (NLP)

### 1.1 Introduction to NLP

Natural Language Processing (NLP) is a multidisciplinary field that combines computer science, linguistics, and artificial intelligence to enable machines to understand, interpret, and generate human language. NLP is ubiquitous in the modern digital world, powering applications such as voice assistants, translation services, and sentiment analysis.

#### 1.1.1 What is NLP in the Real World?

NLP is applied in various real-world scenarios, including:

- **Text Analysis and Summarization**: Automated generation of concise summaries from large documents.
- **Sentiment Analysis**: Assessing the emotional tone of texts in social media or customer reviews.
- **Machine Translation**: Translating text from one language to another, as seen in Google Translate.
- **Chatbots and Virtual Assistants**: Enabling conversational interfaces in applications like Siri, Alexa, and customer support bots.

#### 1.1.2 NLP Tasks

Key tasks in NLP include:

- **Tokenization**: Splitting text into individual words or phrases.
- **Named Entity Recognition (NER)**: Identifying and classifying entities like names, places, and organizations.
- **Part-of-Speech (POS) Tagging**: Determining the grammatical category (noun, verb, etc.) of each word.
- **Dependency Parsing**: Analyzing the grammatical structure of a sentence.
- **Text Classification**: Assigning predefined categories to text data, such as spam detection in emails.
- **Sentiment Analysis**: Detecting the sentiment or emotion expressed in text.

### 1.2 What is Language?

Language is a complex system of communication used by humans, comprising various components that convey meaning and facilitate interaction. It consists of several fundamental building blocks:

#### 1.2.1 Building Blocks of Language

1. **Phonemes**: The smallest units of sound in a language. For example, the word "cat" has three phonemes: /k/, /æ/, and /t/.
2. **Morphemes**: The smallest units of meaning. "Unbelievable" has three morphemes: "un-", "believe", and "-able".
3. **Lexemes**: The set of all inflected forms of a single word. For example, "run" includes "runs", "ran", and "running".
4. **Syntax**: The arrangement of words and phrases to create well-formed sentences. It governs the grammatical structure of language.
5. **Context**: The situational background that influences the meaning of words and sentences.

### 1.3 Introduction to Approaches to NLP

NLP can be approached using various methods, each with its strengths and limitations:

#### 1.3.1 Heuristics-Based NLP

- Utilizes rule-based methods to process language.
- Effective for well-defined, small-scale problems.
- Example: Regular expressions for pattern matching in text.

#### 1.3.2 Machine Learning for NLP

- Uses statistical methods and algorithms to learn from data.
- Techniques include supervised and unsupervised learning.
- Common algorithms: Naive Bayes, Support Vector Machines (SVM), and decision trees.

#### 1.3.3 Deep Learning for NLP

- Leverages neural networks, especially deep neural networks, to model complex language patterns.
- Significant advancements have been made with architectures like Recurrent Neural Networks (RNNs), Long Short-Term Memory (LSTM) networks, and Transformers.
- Applications include language translation, text generation, and question answering.


## Lab 1: Environment + Hands-on Regex (Heuristic Based)

### Environment Preparation:
- Download anaconda: https://www.anaconda.com/download/success
- Create a new environment called 'NLP_SEPT_2024'
    - Set Python version 3.11.x
    - Install:
        - Notebook
        - JupyterLab
        - VS Code
        - CMD Prompt
        - Powershell Prompt
    - In Python install basic packages (pip install `package`):
        - pandas
        - numpy
        - matplotlib
        - seaborn
        - wordcloud # Visualizing the most frequent words in a corpus.
        - nltk # Tokenization, POS tagging, stemming, and more.
        - spacy # Named Entity Recognition (NER), dependency parsing, and part-of-speech tagging.
        - textblob # Sentiment analysis, translation, and language detection.
        - gensim # Topic modeling, document similarity, and word embeddings.
        - torch # Implementing custom deep learning architectures, fine-tuning models like BERT for NLP tasks.
        - transformers # Text classification, translation, question answering, and language generation using pre-trained models.
        - sentence-transformers # Text similarity, clustering, and retrieval tasks.
        - tensorflow
        - keras
        - scikit-learn
        - chime

### Regex Hands-on

Common Regex Patterns (https://docs.python.org/3/library/re.html):
-        . - Matches any character except a newline.
-        ^ - Matches the start of the string.
-        $ - Matches the end of the string.
-        * - Matches 0 or more repetitions of the preceding element.
-        + - Matches 1 or more repetitions of the preceding element.
-        ? - Matches 0 or 1 repetition of the preceding element.
-        {n} - Matches exactly n repetitions of the preceding element.
-        {n,} - Matches n or more repetitions of the preceding element.
-        {n,m} - Matches between n and m repetitions of the preceding element.
-        [] - Matches any one of the enclosed characters.
-        | - Alternation; matches either the pattern before or after the |.
-        () - Groups multiple patterns into one.
-        \d: Matches any digit (equivalent to [0-9]).
-        \D: Matches any non-digit character.
-        \s: Matches any whitespace character (spaces, tabs, newlines).
-        \S: Matches any non-whitespace character.
-        \b: Matches a word boundary (the position between a word and a non-word character).
-        \B: Matches a non-word boundary.
-        \w: Matches any word character (alphanumeric plus underscore).
-        \W: Matches any non-word character.

- Practice REGEX: https://regex101.com/r/rsVgaP/1

In [2]:
import re
import pandas as pd
import numpy as np


In [19]:
# Example strings
text = "You should call 911 now. 911 is the emergency number"


In [ ]:
# Find all numbers in the text
pattern = ...
# Use re.findall()
matches = ...
print(f"Numbers found: {matches}")

In [ ]:
# Replace all numbers with the word '999'
pattern = ...
# hint use re.sub()
replaced_text = ...
print(replaced_text)


In [177]:
# Extract Email 
data = {'emails': ['john.doe@example.com', 'jane_smith@abc.co.uk', 'invalid.email@com']}
df = pd.DataFrame(data)

# Hint: Use df['col'].str.extract()

# Extract the username separately
# ^: Start of the string.
# ([\w.%+-]+): Captures the username part of the email.
# [\w.%+-]: Matches any word character (letters, digits, underscores), plus the special characters . % + -.
# +: One or more of the preceding characters.
# @: Matches the literal @ symbol, which is required to separate the username and domain.
df['username'] = ...

# Extract the domain separately
# @: Matches the literal @ symbol, which precedes the domain part.
# ([\w.-]+\.[a-zA-Z]{2,}): Captures the domain part of the email.
# [\w.-]+: Matches the main domain part, including letters, digits, hyphens, and dots.
# \.[a-zA-Z]{2,}: Matches the top-level domain (TLD) with at least two letters.
# $: End of the string.
df['domain'] = ...
df


emails       username       domain
0  john.doe@example.com       john.doe  example.com
1  jane_smith@abc.co.uk     jane_smith    abc.co.uk
2     invalid.email@com  invalid.email          NaN

In [147]:
# Email Validation
def validate_email(email):
    pattern = ...
    # ^(?!.*\.\.): Negative lookahead to ensure there are no consecutive dots in the email string.
    # [a-zA-Z0-9._%+-]+: Matches the local part (username) of the email. Allows letters, digits, and special characters such as ., _, %, +, -.
    # @[a-zA-Z0-9.-]+: Matches the domain part. Allows letters, digits, hyphens, and dots. This pattern allows a single dot but not consecutive dots within the domain part.
    # \.[a-zA-Z]{2,6}$: Matches the TLD with 2 to 6 alphabetic characters, which covers most common TLDs like .com, .org, .museum, etc.
    return bool(re.match(pattern, email))
# Test the refined function
emails = ['test.email@example.com', 'invalid-email@.com', 'name@domain.co', 'test..email@example.com', 'test@domain.c', 'test@domain.toolongtld']
results = [validate_email(email) for email in emails]
print(f"Validation Results: {results}")



Validation Results: [True, False, True, False, False, False]


In [32]:
# Phone Number Validation
def validate_phone_number(number):
    # Pattern to match common phone number formats
    pattern = ...

    # ^: Start of the string.
    # (\+\d{1,3}[-.\s]?)?: Matches the optional country code part.
        # \+: Matches a literal plus sign '+' at the start, indicating an international code.
        # \d{1,3}: Matches 1 to 3 digits for the country code (e.g., '1' for the US, '44' for the UK).
        # [-.\s]?: Matches an optional separator, which can be a hyphen '-', a dot '.', or a space ' '.
        # ?: Makes the entire country code part optional.
    # (\(?\d{3}\)?[-.\s]?)?: Matches the optional area code part.
        # \(?\d{3}\)?: Matches 3 digits for the area code, which may or may not be enclosed in parentheses. 
            # - \(? : Matches an optional opening parenthesis '('.
            # - \d{3}: Matches exactly 3 digits for the area code.
            # - \)?: Matches an optional closing parenthesis ')'.
        # [-.\s]?: Matches an optional separator (hyphen, dot, or space).
            # ?: Makes the entire area code part optional.
    # (\d{3}[-.\s]?\d{4}): Matches the main phone number part.
        # \d{3}: Matches exactly 3 digits.
        # [-.\s]?: Matches an optional separator (hyphen, dot, or space).
        # \d{4}: Matches exactly 4 digits for the remaining part of the phone number.
    # $: End of the string. Ensures that the pattern matches the entire phone number from start to end.
    
    return bool(re.fullmatch(pattern, number))


# Test the function with a list of phone numbers
numbers = ['+1-800-555-5555',  # Valid: Includes country code and separators.
           '(123) 456 7890',   # Valid: Area code in parentheses and spaces as separators.
           '12345']            # Invalid: Too short to be a valid phone number.

# Validate each phone number using the function
results = [validate_phone_number(number) for number in numbers]

# Display the validation results for each phone number
print(f"Validation Results: {results}")


Validation Results: [True, True, False]


In [20]:
# Extract URLs

# Extracting URLs from the given text
text = 'Visit our website at https://www.example.com or follow us at http://blog.example.com'

# Define the pattern to match URLs
pattern = ...

# https?://: 
# - https?: Matches the literal 'http' followed optionally by 's'. This means it can match both 'http' and 'https'.
# - ://: Matches the literal characters '://', which are required after 'http' or 'https' in a URL.

# [a-zA-Z0-9./-]+:
# - [a-zA-Z0-9./-]: Character set that matches any of the following characters:
#   - a-z: Lowercase English letters.
#   - A-Z: Uppercase English letters.
#   - 0-9: Digits.
#   - . (dot): Matches the literal dot, which is used in domain names and paths.
#   - / (forward slash): Matches the literal slash, which is used to separate different parts of the URL.
#   - - (hyphen): Matches the literal hyphen, which can be part of domain names or paths.
# - +: Quantifier that matches one or more of the preceding characters in the set, ensuring the pattern matches the entire URL.

# Hint: Use re.findall()
urls = ...

print(f"Extracted URLs: {urls}")


Extracted URLs: ['https://www.example.com', 'http://blog.example.com']


In [171]:
# Extract Birthday
# Sample text containing dates
text = "John's birthday is on 23/05/1995 and Mary's is on 15-04-1992."

# Define the pattern to match date formats
pattern = ...

# \b: Matches a word boundary, ensuring that the pattern matches whole numbers and not parts of larger strings.
    # - This prevents partial matches like '123' in '123abc'.
# \d{1,2} or \d{2,4}: 
# - \d: Matches any digit from 0 to 9.
# - {1,2}: Matches lower or upper digits for the day or month part, allowing for numbers like '3' or '23'.
# [-/]: - Matches either a hyphen '-' or a forward slash '/', which are common separators in date formats.


# Hint Use re.findall()
dates = ...

print(f"Extracted Dates: {dates}")


Extracted Dates: ['23/05/1995', '15-04-1992']


In [179]:
# Splitting text to be split into sentences
text = "Hello there! How are you today? Let's learn regex."

# Define the pattern to split the text into sentences
pattern = ...

# Explanation of the pattern:
# [.!?]:
# - [ ]: Square brackets define a character class, which matches any one of the enclosed characters.
# - .: Matches a literal period (.) which marks the end of a sentence.
# - !: Matches a literal exclamation mark (!) which marks the end of an exclamatory sentence.
# - ?: Matches a literal question mark (?) which marks the end of a question.

# Hint: Use re.split(pattern,text)
sentences = ...

sentences = [sentence.strip() for sentence in sentences if sentence.strip()]

print(f"Sentences: {sentences}")


Sentences: ['Hello there', 'How are you today', "Let's learn regex"]


# Section 2: Approaches & Detailed NLP Pipeline

## 1. Introduction to Approaches to NLP

### Heuristics-Based NLP
Heuristic approaches rely on rules and patterns for natural language processing, without relying on data-driven methods. Commonly, regular expressions (regex) are used.

**Example:** Named Entity Recognition (NER) using heuristics might involve defining a set of patterns to detect names, locations, or dates.

In [ ]:
import re
text = "Ahmed lives in Egypt"
pattern = r"..."  # Simple heuristic for proper nouns
# Use \b and make sure the first letter is capital and then get the rest of the word
entities = re.findall(pattern, text)
print(entities)  # ['Ahmed', 'Egypt']

['Ahmed', 'Egypt']


### Machine Learning for NLP
Machine learning approaches involve training models on labeled data. A basic example is using the Naive Bayes algorithm for text classification. One common method for text representation in machine learning is the bag-of-words model, which transforms text into numerical features by counting the occurrences of words.

**Equation:**

$$
P(y|x) = \frac{P(x|y)P(y)}{P(x)}
$$

This is the basis of the Naive Bayes classifier, where:
- \( y \) is the class label (e.g., positive or negative sentiment),
- \( x \) is the text feature (e.g., a sequence of words),
- \( P(y|x) \) is the posterior probability of class \( y \) given the text feature \( x \),
- \( P(x|y) \) is the likelihood of text feature \( x \) given class \( y \),
- \( P(y) \) is the prior probability of class \( y \),
- \( P(x) \) is the probability of the text feature \( x \).

**Example:** Text classification using Scikit-learn


In [ ]:
# Importing necessary libraries
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

class Utility:
    @staticmethod
    def vectorize_and_split(texts,labels):
        # Step 1: Vectorizing the text data using CountVectorizer (Bag-of-Words model)
        vectorizer = ... # Use count vectorizer
        X_v = vectorizer.fit_transform(...)  # Transform text into a matrix of token counts
        # Step 2: Splitting data into training and test sets
        X_train, ..., ..., y_test = train_test_split(..., labels, test_size=0.2, random_state=42)
        return X_train,...,...,y_test,vectorizer
    @staticmethod
    def model_pipeline(X_train,X_test,y_train,y_test):
        # Step 3: Initializing the Naive Bayes model (MultinomialNB is suitable for text classification)
        model = ... # Use the multinomial NB
        # Step 4: Training the model on the training data
        ... # Train the model
        # Step 5: Making predictions on the test data
        y_pred = ... # Predict
        # Step 6: Evaluating the model's performance
        accuracy = accuracy_score(y_test, y_pred)
        print(f"Accuracy: {accuracy * 100:.2f}%")
        return ...
    @staticmethod
    def model_predict_and_evaluate(model,new_texts,vectorizer):
        X_new = vectorizer.transform(...) # transform new data
        predictions = model.predict(...) # predict new data 
        
        # Output predictions
        for text, pred in zip(new_texts, predictions):
            sentiment = "Positive" if pred == 1 else "Negative/Neutral"
            print(f"Text: '{text}' => Sentiment: {sentiment}")

class Helper:
    @staticmethod
    def run_pipeline(new_texts,texts,labels):
        X_train,...,...,y_test,vectorizer = Utility.vectorize_and_split(texts=texts,labels=labels)
        model = Utility.model_pipeline(X_train=X_train,
                                       X_test=...,
                                       y_train=...,
                                       y_test=y_test)
        Utility.model_predict_and_evaluate(model,new_texts,vectorizer)


In [ ]:
# Data
# Predicting the sentiment of new texts
new_texts = [
    "Ahmed enjoys coding in Python",
    "The service was horrible and I am disappointed",
    "Quantum mechanics is an intriguing field",
    "I didn't like the food at all, it was tasteless"
]
# Sample dataset with texts and corresponding sentiment labels (1: positive, 0: neutral/negative)
texts = [
    "Ahmed loves NLP and enjoys learning about machine learning",
    "Egypt has beautiful landscapes and rich culture",
    "Heuristics are simple yet effective in problem solving",
    "Python is a great language for data science and AI",
    "Natural language processing is fascinating",
    "I don't like spam emails",
    "This movie was very boring and too long",
    "The weather in Egypt is warm and sunny most of the year",
    "I had a terrible customer service experience",
    "AI is transforming industries and creating new opportunities",
    "This is the worst product I have ever bought",
    "I love exploring new places and experiencing different cultures",
    "The food at the restaurant was fantastic",
    "The traffic in Cairo is terrible during rush hours",
    "I enjoy spending time with my family on the weekends",
    "The company's customer service was exceptional",
    "This is an average book with no exciting plot",
    "I am fascinated by advancements in quantum computing",
    "The park near my house is always clean and peaceful",
    "This phone has terrible battery life, I am disappointed",
    # Additional data:
    "The music was beautiful and uplifting",
    "I am not happy with the slow internet speed",
    "The staff at the hotel were very polite and helpful",
    "This software is extremely buggy and crashes often",
    "I had a great time at the concert",
    "I am fed up with all the ads in this app",
    "The customer support was rude and unhelpful",
    "The car's performance was beyond my expectations",
    "I hate waiting in long lines",
    "The book was interesting but too long",
    "I had a wonderful vacation with my family",
    "This smartphone is overpriced and not worth the money",
    "I enjoyed watching the latest movie at the cinema",
    "The delivery service was fast and efficient",
    "This laptop is lightweight and has a long battery life",
    "I am dissatisfied with the product's quality",
    "The new restaurant has a cozy atmosphere and delicious food",
    "The airline lost my luggage and I am very upset",
    "The presentation was informative and well-organized",
    "The hotel room was dirty and smelled bad"
]
# Labels: 1 for positive sentiment, 0 for neutral or negative sentiment
labels = [
    1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
    # Additional labels:
    1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0
]

In [ ]:
Helper.run_pipeline(new_texts=new_texts,
                    texts=texts,
                    labels=labels)

Accuracy: 75.00%
Text: 'Ahmed enjoys coding in Python' => Sentiment: Positive
Text: 'The service was horrible and I am disappointed' => Sentiment: Negative/Neutral
Text: 'Quantum mechanics is an intriguing field' => Sentiment: Positive
Text: 'I didn't like the food at all, it was tasteless' => Sentiment: Positive


#### Terminology about last example!!

How CountVectorizer Works:
CountVectorizer is a simple and effective tool used in Natural Language Processing (NLP) to convert a collection of text documents into a matrix of token counts. It essentially creates a Bag-of-Words (BoW) representation of the text data, where:

- Tokenization: It splits the text into words or tokens.
- Vocabulary creation: It builds a vocabulary (unique words from the dataset).
- Count representation: Each text document is then represented as a vector of word counts, i.e., how many times each word from the vocabulary appears in each document.

---

Is CountVectorizer the Best Option?
While CountVectorizer is effective in many cases, it has limitations:

- Ignores word importance: It treats all words equally, meaning frequent words like "the" or "is" get as much weight as important words, which may not be desirable.
- Doesn't consider word context: It doesn't capture the relationship between words (e.g., "New York" is treated as two separate words rather than a single entity).
- Sparse representations: For large vocabularies, the resulting matrix can be very sparse, with many zero entries.

**Other Options and Their Differences:**

**TfidfVectorizer** (Term Frequency-Inverse Document Frequency):

- What it does: It transforms text into a matrix of TF-IDF features. It takes into account the frequency of a word in a document and its frequency across all documents. This way, less frequent but important words are given higher weight compared to common words.
- Why it's better: It reduces the importance of frequently occurring words that may not be informative (like "the" or "is"), leading to better performance for some tasks.
- Example: Words that appear in fewer documents will have higher weight, while common words will have a lower weight.


**HashingVectorizer**:

- What it does: Similar to CountVectorizer, but instead of building a vocabulary, it uses a hashing trick to map terms to indices in a fixed-size vector space.
- Why it's different: No need to store a vocabulary, which saves memory. This can be useful when dealing with very large datasets.

- Downside: It's not possible to reverse the transformation and map back to the original words since hashing is a one-way process.

**Word2Vec or GloVe (Word Embeddings)**:

- What it does: Instead of representing words based on their counts, it captures the semantic meaning of words by embedding them into dense vectors. Similar words are mapped close to each other in the vector space.
- Why it's better: It captures semantic relationships between words, so words like "king" and "queen" would have similar vectors, while traditional vectorizers treat them as completely different.
- Downside: More complex to train and use, but it can provide more informative features, especially for tasks that benefit from semantic understanding.


**BERT, GPT, and other transformer-based models**:

- What they do: These models use deep learning to generate context-aware word embeddings. Each word is represented based on the context in which it appears.
- Why it's better: Unlike CountVectorizer or TfidfVectorizer, they capture the meaning of a word depending on its surrounding words, making them much more powerful for complex NLP tasks like sentiment analysis, text classification, and question answering.
Downside: Computationally expensive and require large datasets for training. They also need more processing power compared to simpler vectorizers.

When to Use Which?
- For simple tasks with limited data: CountVectorizer or - TfidfVectorizer are usually sufficient. TfidfVectorizer tends to perform better in cases where the frequency of common words needs to be downplayed.

- For large-scale or production tasks: HashingVectorizer is useful when dealing with very large datasets, especially when memory is a concern.

- For advanced NLP tasks requiring semantic understanding: Word embeddings (Word2Vec, GloVe) or transformer-based models like BERT are more powerful, capturing context and meaning.

# Section 3: Vectorizers and NLP Pipeline

In [ ]:
# Display All Vectorizers with their differences
import pandas as pd
# Load the CSV file into a pandas dataframe
df = pd.read_csv("NLP_Vectorization_Techniques__Simplest_to_Most_Complex_.csv")
from tabulate import tabulate
# Generate the markdown table using tabulate
markdown_table = tabulate(df, headers='keys',tablefmt= 'grid')
# Print the markdown table
print(markdown_table)


+----+-------------------+----------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
|    | Technique         | Features                                                                   | Advantages                                                                                              | Disadvantages                                               | Use case                                                                                                                                                                  | Prin

## Each vectorizer in action

In [2]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from gensim.models import Word2Vec
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from transformers import BertTokenizer, BertModel
import torch
import numpy as np
import pandas as pd

class Utility:
    
    """Utility Class:
        Tokenization Method: Splits each sentence into a list of words (used for Word2Vec and Doc2Vec).
        
        count_vectorizer(): Converts the text into a matrix of word counts using CountVectorizer. It outputs a vocabulary (dictionary of words and their indices) and a matrix where each row represents a document, and each column represents the count of a word in the document.
        
        tfidf_vectorizer(): Converts the text into a matrix of TF-IDF (Term Frequency-Inverse Document Frequency) values. Words that occur less frequently but are important receive higher weight, while common words receive lower weight.
        
        hashing_vectorizer(): Uses the HashingVectorizer to transform the text into a fixed-size vector space without storing the vocabulary. Each word is hashed into one of the predefined dimensions.
        
        word2vec(): Trains a Word2Vec model to generate a dense vector for each word, capturing semantic relationships. For example, words like "learning" and "education" would have similar vector representations.
        
        doc2vec(): Trains a Doc2Vec model to generate document-level embeddings. Each document is represented as a dense vector capturing its meaning as a whole.
        
        bert_vectorizer(): Uses BERT (Bidirectional Encoder Representations from Transformers) to generate context-aware embeddings for each word in the sentence."""
        
    def tokenize_texts(texts):
        """Tokenizes the dataset for Word2Vec and Doc2Vec."""
        return [text.split() for text in texts]

    def count_vectorizer(texts):
        """
        Applies CountVectorizer and returns vocabulary and feature matrix.
        
        Expected output:
        Vocabulary: {'machine': 4, 'learning': 3, ...}
        Matrix: Shows the count of each word in each document.
        Example:
        [[0 0 0 1 1 ...]
        [0 1 1 0 0 ...]]
        """
        vectorizer = CountVectorizer()
        matrix = vectorizer.fit_transform(texts).toarray()
        return vectorizer.vocabulary_, matrix

    def tfidf_vectorizer(texts):
        """
        Applies TfidfVectorizer and returns vocabulary and feature matrix.
        
        Expected output:
        Vocabulary: {'machine': 4, 'learning': 3, ...}
        Matrix: Shows TF-IDF values for each word in each document.
        Example:
        [[0 0 0 0.45 0.35 ...]
        [0 0.34 0.56 0 0 ...]]
        """
        vectorizer = TfidfVectorizer()
        matrix = vectorizer.fit_transform(texts).toarray()
        return vectorizer.vocabulary_, matrix

    def hashing_vectorizer(texts):
        """
        Applies HashingVectorizer and returns the feature matrix.
        
        Expected output:
        No vocabulary (since it's hashed).
        Matrix: A fixed-size vector space with hashed word counts.
        Example:
        [[ 0.   0.   0.23  0.33 ...]
        [ 0.12 -0.12  0.5  0.1 ...]]
        """
        vectorizer = HashingVectorizer(n_features=10)
        matrix = vectorizer.transform(texts).toarray()
        return matrix

    def word2vec(texts):
        """
        Trains Word2Vec on the tokenized dataset and returns a vector for 'learning'.
        
        Expected output:
        A dense vector for the word "learning", capturing its semantic meaning.
        Example:
        Word2Vec Vector for 'learning': [0.12, 0.23, -0.45, ...]
        """
        tokenized_texts = Utility.tokenize_texts(texts)
        model = Word2Vec(sentences=tokenized_texts, vector_size=5, window=2, min_count=1, workers=4)
        return model.wv['learning']

    def doc2vec(texts):
        """
        Trains Doc2Vec on the tagged dataset and returns the document vector for document 0.
        
        Expected output:
        A dense vector representing the entire first document.
        Example:
        Doc2Vec Vector for Document 0: [0.23, -0.14, 0.65, ...]
        """
        tokenized_texts = Utility.tokenize_texts(texts)
        tagged_data = [TaggedDocument(words=text, tags=[str(i)]) for i, text in enumerate(tokenized_texts)]
        model = Doc2Vec(tagged_data, vector_size=5, window=2, min_count=1, workers=4)
        return model.dv['0']

    def bert_vectorizer(text):
        """
        Uses BERT to get contextual embeddings for the input text.
        
        Expected output:
        Contextual embeddings for the input sentence, capturing the context of each word.
        Example:
        BERT Embeddings for 'Machine learning is fun': [0.14, -0.25, 0.35, ...]
        """
        tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
        model = BertModel.from_pretrained('bert-base-uncased')
        inputs = tokenizer(text, return_tensors="pt")
        with torch.no_grad():
            outputs = model(**inputs)
        return outputs.last_hidden_state

    # Display helper
    def display_result(vectorizer_name, vocabulary, matrix):
        print(f"\n{vectorizer_name}:")
        print("Vocabulary:", vocabulary)
        print("Matrix:\n", matrix)


In [4]:
class Helper:
    def display_all_vectorizers():
        vocab_count, count_matrix = Utility.count_vectorizer(texts)
        Utility.display_result("CountVectorizer", vocab_count, count_matrix)

        vocab_tfidf, tfidf_matrix = Utility.tfidf_vectorizer(texts)
        Utility.display_result("TfidfVectorizer", vocab_tfidf, tfidf_matrix)

        hashing_matrix = Utility.hashing_vectorizer(texts)
        Utility.display_result("HashingVectorizer", None, hashing_matrix)
        
        word2vec_vector = Utility.word2vec(texts)
        
        print("\nWord2Vec Vector for 'learning':", word2vec_vector)

        doc2vec_vector = Utility.doc2vec(texts)
        print("\nDoc2Vec Vector for Document 0:", doc2vec_vector)

        bert_vector = Utility.bert_vectorizer("Machine learning is fun")
        print("\nBERT Embeddings for 'Machine learning is fun':\n", bert_vector)


In [5]:
# Sample dataset
texts = [
    "Machine learning is fun",
    "Natural language processing includes syntax and semantics",
    "Deep learning enables complex pattern recognition",
    "Artificial intelligence is transforming the world",
    "Text analysis is an essential part of NLP",
    "Neural networks are a core component of deep learning"
]
Helper.display_all_vectorizers()


CountVectorizer:
Vocabulary: {'machine': 17, 'learning': 16, 'is': 14, 'fun': 11, 'natural': 18, 'language': 15, 'processing': 25, 'includes': 12, 'syntax': 28, 'and': 2, 'semantics': 27, 'deep': 8, 'enables': 9, 'complex': 5, 'pattern': 24, 'recognition': 26, 'artificial': 4, 'intelligence': 13, 'transforming': 31, 'the': 30, 'world': 32, 'text': 29, 'analysis': 1, 'an': 0, 'essential': 10, 'part': 23, 'of': 22, 'nlp': 21, 'neural': 20, 'networks': 19, 'are': 3, 'core': 7, 'component': 6}
Matrix:
 [[0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
 [1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0]]

TfidfVectorizer:
Vocabulary: {'machine': 17, 'learning': 16, 'is': 14, 'fun': 1

Interpretation:

CountVectorizer:
Vocabulary: Displays the mapping of each word to a unique index.
Matrix: Shows the count of each word in each document. For example, the word "learning" occurs once in the first and third sentences, while "fun" occurs once in the first.

TfidfVectorizer:
Vocabulary: Same as CountVectorizer, but now the matrix contains TF-IDF values. Words that appear frequently across documents receive lower weight (like "is"), while rare words receive higher weight (like "semantics").
Matrix: Contains floating-point numbers representing the relative importance of each word in a document. For example, words like "fun" and "machine" receive higher values because they are less frequent but important.

HashingVectorizer:
Vocabulary: Not available (since it uses a hash function).
Matrix: Each document is represented by a fixed-size vector. This method is more memory-efficient but does not provide a direct way to map the indices back to the original words.

Word2Vec:
Vector: For the word "learning", a dense vector is produced. These vectors are continuous-valued representations that capture the semantic meaning of words. Words with similar meanings will have similar vectors.

Doc2Vec:
Vector: Each document is represented as a dense vector. This vector captures the overall semantics of the document. In this case, document 0 ("Machine learning is fun") is represented by a vector that encodes its meaning as a whole.

BERT:
Embeddings: Each word in the sentence "Machine learning is fun" is represented by a contextualized embedding. The meaning of each word depends on the context of the other words in the sentence, making it powerful for tasks like question answering, sentiment analysis, etc. For example, "learning" in "machine learning" has a different meaning than in "learning from mistakes."

### Deep Learning for NLP
Deep learning approaches, such as Recurrent Neural Networks (RNNs) and Transformers, have revolutionized NLP by modeling complex dependencies in text data. RNNs use sequential data with hidden states, while Transformers, like BERT, use attention mechanisms for parallel processing.

**Equation:** 
The attention mechanism in Transformers is defined as:

$$
\text{Attention}(Q, K, V) = \text{softmax} \left( \frac{QK^T}{\sqrt{d_k}} \right) V
$$

Where:
- \( Q \) is the **query**,
- \( K \) is the **key**,
- \( V \) is the **value**,

and \( d_k \) is the dimension of the key.

**Example:** Using Huggingface's BERT for text classification


In [ ]:
from transformers import ...
"""Imports the pipeline function from the Hugging Face Transformers library. 
The pipeline is a high-level abstraction that allows you to easily use state-of-the-art NLP models without worrying about the underlying complexity."""


classifier = ...(...) # use sentiment analysis from pipeline
""" Uses Bidirectional Encoder Representations from Transformers (BERT).
This should creates a pre-configured pipeline for sentiment analysis.
By default, Hugging Face uses a pre-trained model from the BERT family, specifically DistilBERT, which has been fine-tuned for sentiment analysis. It will automatically download the required model weights and tokenizer when you first run the code."""


result = ...("Ahmed enjoys studying NLP")
"""Text tokenization: Behind the scenes, the input text is first tokenized, which means it's split into smaller units (tokens) that the model can process.
Model prediction: The pre-trained model then processes these tokens and predicts whether the text expresses a positive or negative sentiment. Since the text is about "enjoying" something, the model will likely predict positive sentiment.
Post-processing: The result is then converted back into a human-readable label, which in this case is either "POSITIVE" or "NEGATIVE", along with a confidence score."""
print(result)

## 2. NLP Pipeline in Detail

### 1. Data Acquisition
The first step in any NLP project is acquiring the data. This can come from web scraping, APIs, or existing datasets.

**Example:** Load a dataset (e.g., IMDB movie reviews)


In [ ]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups

data = fetch_20newsgroups(subset='train')
df = pd.DataFrame({'text': data.data, 'label': data.target})

# Take a look at the data


### 2. Text Cleaning
Text cleaning involves removing noise such as punctuation, numbers, stopwords, and converting text to lowercase.

**Example:** Simple text cleaning


In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Metwalli\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [ ]:
import re
from nltk.corpus import stopwords

"""nltk.corpus.stopwords: provides a corpus of stopwords (common words like "the", "is", "in", etc.) for various languages. Stopwords are often removed in text preprocessing since they don't contribute much to the meaning of the text for certain tasks like classification."""

def clean_text(text):
    """Purpose: Text cleaning and normalization are crucial steps before further processing or analysis, especially in Natural Language Processing (NLP). This ensures the text is free from unnecessary noise like digits, punctuation, and stopwords, and that it’s all in a consistent format (lowercase)."""
    #Hint: Use .sub() from regex and remove numbers and punctuation
    text = ... # This removes all numbers from the text 
    text = ... # regular expression that matches any character that is not a word (\w) or whitespace (\s), effectively removing punctuation.
    text = ... #Converts the text to lowercase to standardize it.
    text = ' '.join([word for word in text.split() if word not in ...('english')]) # Remove stop words
    return text

df['cleaned_text'] = df['text'].apply(...)

### 3. Pre-processing
Pre-processing includes tokenization, lemmatization, and stemming.

**Equation:** For word embeddings like TF-IDF, the formula is:

$$
\text{tf-idf}(t, d) = \text{tf}(t, d) \times \log \left( \frac{N}{\text{df}(t)} \right)
$$

Where:
- **tf(t, d)** is the term frequency of term \( t \) in document \( d \),
- **df(t)** is the document frequency of term \( t \) across all documents,
- **N** is the total number of documents.

**Example:** Tokenization and stemming


In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Metwalli\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Metwalli\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

#We import these functions because we are going to tokenize the text (split it into individual words) and then apply stemming to convert words to their root form for further processing.
#  (e.g., "running" vs. "run") 
ps = ... #This creates an instance of the PorterStemmer, which will be used to stem each tokenized word.

df['tokens'] = df['cleaned_text'].apply(lambda x: ...) # Use lambda function and .word_tokenize
df['stemmed_tokens'] = df['tokens'].apply(lambda x: [... for word in x]) # use .stem(words) from ps 

### 4. Feature Engineering
This involves representing text as numeric features. Popular techniques include Bag-of-Words, TF-IDF, and Word Embeddings (Word2Vec, GloVe).

**Example:** TF-IDF vectorization


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
"""The TfidfVectorizer is used to convert text into a numerical form that machine learning models can understand. The vectorizer automatically handles tokenization and computes the TF-IDF score for each word."""
tfidf = ... # use an instance of tfidf
X = ... # use Fit & transform in tfidf on the cleaned_text from the df

"""it will:
Tokenize the text (i.e., split it into words).
Compute the term frequency for each word in each document.
Compute the inverse document frequency (IDF) across the corpus.
Multiply the TF and IDF values to get the TF-IDF score for each word in each document."""

### 5. Modeling
You can now apply machine learning or deep learning models like Logistic Regression, SVM, or neural networks.

**Example:** Logistic Regression for text classification


In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X, df['label'])

LogisticRegression()

### 6. Evaluation
Model evaluation metrics include accuracy, precision, recall, and F1 score.

**Equations:**

$$
\text{Precision} = \frac{TP}{TP + FP}, \quad \text{Recall} = \frac{TP}{TP + FN}
$$

Where:
- **TP** = true positives,
- **FP** = false positives,
- **FN** = false negatives.

**Example:** Evaluating model performance


In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X)
print(classification_report(df['label'], y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       480
           1       0.96      0.97      0.97       584
           2       0.95      0.96      0.95       591
           3       0.93      0.95      0.94       590
           4       0.98      0.98      0.98       578
           5       0.98      0.98      0.98       593
           6       0.94      0.96      0.95       585
           7       0.98      0.98      0.98       594
           8       1.00      0.99      0.99       598
           9       1.00      1.00      1.00       597
          10       1.00      1.00      1.00       600
          11       1.00      0.98      0.99       595
          12       0.98      0.97      0.98       591
          13       1.00      0.99      0.99       594
          14       1.00      0.99      1.00       593
          15       0.96      1.00      0.98       599
          16       0.98      0.99      0.99       546
          17       1.00    

### 7. Deployment
Deploying the model can involve using platforms like FastAPI or Flask for serving predictions.

**Example:** FastAPI skeleton for deploying an NLP model


```python
from fastapi import FastAPI
import joblib

app = FastAPI()
model = joblib.load('model.pkl')

@app.post("/predict/")
def predict(text: str):
    return {"prediction": model.predict([text])}

### 8. Monitoring and Model Updating
Monitoring involves tracking model performance post-deployment and updating the model when performance degrades.


# Week 5: Dive Deeper into Word2Vec and Doc2Vec

### Elevator Pitch (Seamless Intro):
NER: Identifies and classifies entities in text (e.g., names, locations, dates) using machine learning or rule-based algorithms.

Word2Vec: Creates dense word embeddings that capture semantic similarity between words by positioning similar words close in a vector space.

Difference: NER is for entity classification, while Word2Vec is for semantic word relationships.

Combination: Using Word2Vec embeddings can improve NER by providing better context understanding for entity recognition and classification.

Notes: Mathematical representation of word is the vector! The features in this example are [authority, have tail, rich, male]. Surrounding words are the context.
> Example the word King: King has authority, king does not have tail, king is rich, king gender is male
>> Authority: 1, Has tail = 0, Rich = 1, Gender = -1
> Example the word man: 
>> Authority: 0.2, Has tail = 0, Rich = 0.3, Gender = -1

### 1. Introduction to Word Embeddings

In natural language processing (NLP), understanding the relationships between words is crucial. Traditionally, words were represented as sparse vectors using techniques like one-hot encoding, which lacked semantic meaning. **Word2Vec**, developed by Google, addresses this by creating dense vector representations (embeddings) where similar words have similar vectors, effectively capturing the semantic meaning of words.

### 2. Use Cases for Word2Vec

Word2Vec’s dense embeddings are powerful for many applications in NLP:

- **Sentiment Analysis**: Words with similar sentiments (e.g., "good" and "great") have similar vector representations.
- **Recommendation Systems**: Identifying item similarities based on descriptions or reviews.
- **Semantic Search**: Using vector similarity to match contextually similar phrases or words.

These embeddings allow algorithms to measure similarity between words, which helps in clustering, classification, and many downstream NLP tasks.

### 3. How Word2Vec Works: Models and Training

Word2Vec learns word representations through a shallow neural network. It has two main models:

1. **Continuous Bag of Words (CBOW)**: Predicts a word based on its surrounding words (context).
2. **Skip-Gram**: Predicts surrounding context words given a single word.

These models learn to map words to a high-dimensional space where semantically related words are closer to each other.

### 4. Skip-Gram Model

The **Skip-Gram model** is useful when we want to understand the broader context of a word. For example, given a target word \( w_t \), it tries to predict words within a context window of size \( c \) around \( w_t \).

#### Objective Function for Skip-Gram

For a given target word \( w_t \) and its context words \( w_{t-c}, \dots, w_{t+c} \), the objective is to maximize the log probability:

$$
\frac{1}{T} \sum_{t=1}^T \sum_{-c \leq j \leq c, j \neq 0} \log P(w_{t+j} | w_t)
$$

where \( T \) is the total number of words in the corpus.

This probability \( P(w_{t+j} | w_t) \) is computed with a softmax function:

$$
P(w_O | w_I) = \frac{\exp(v'_{w_O} \cdot v_{w_I})}{\sum_{w=1}^{W} \exp(v'_w \cdot v_{w_I})}
$$

where:
- \( v_{w_I} \) is the input vector for the word \( w_I \),
- \( v'_{w_O} \) is the output vector for the word \( w_O \), and
- \( W \) is the vocabulary size.

### 5. Continuous Bag of Words (CBOW) Model

In contrast to Skip-Gram, **CBOW** predicts a target word \( w_t \) based on surrounding context words. CBOW is often faster and more accurate for frequent words.

#### Objective Function for CBOW

The objective function for CBOW is to maximize the log probability of predicting the target word given its context:

$$
\frac{1}{T} \sum_{t=1}^T \log P(w_t | w_{t-c}, \dots, w_{t+c})
$$

CBOW captures context effectively and is computationally more efficient for larger datasets.

### 6. Optimization Techniques: Negative Sampling and Hierarchical Softmax

Training with a large vocabulary can be computationally expensive. Word2Vec employs two key techniques to optimize this:

- **Negative Sampling**: Rather than updating weights for every word, it updates only for a few sampled "negative" words.
  
  The negative sampling objective is:

  $$
  \log \sigma(v'_{w_O} \cdot v_{w_I}) + \sum_{i=1}^k \mathbb{E}_{w_i \sim P_n(w)} \left[ \log \sigma(-v'_{w_i} \cdot v_{w_I}) \right]
  $$

  where \( \sigma(x) \) is the sigmoid function and \( P_n(w) \) is the distribution for sampling.

- **Hierarchical Softmax**: Uses a binary tree structure to reduce complexity when calculating softmax probabilities, beneficial for large vocabularies.

### 7. Limitations of Word2Vec

While Word2Vec is powerful, it has some limitations:

- **Lacks Contextuality**: Each word has a single representation, regardless of the context in which it appears. This limits its ability to handle words with multiple meanings (polysemy).
- **Static Embeddings**: The embeddings are static, meaning they do not dynamically adapt based on sentence context.
- **Memory Intensive**: For large vocabularies, Word2Vec requires significant memory to store embeddings.

### 8. Example of Word2Vec in Action

Suppose we have a sentence: "The cat sits on the mat." Using a window size of 2, the Skip-Gram model might generate training pairs like:

- ("cat", "the"), ("cat", "sits"), ("sits", "cat"), ("sits", "on")

The model will learn vectors for "cat," "sits," "on," etc., so that contextually similar words (e.g., "cat" and "dog") end up with similar embeddings, capturing semantic relationships in the data.

---


### Hands-on Word2Vec using Gensim

In [ ]:
import gensim, pandas as pd, numpy as np

- Dataset can be found: http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Cell_Phones_and_Accessories_5.json.gz

In [ ]:
import gzip, shutil, os

# File to decompress
input_file = 'reviews_Cell_Phones_and_Accessories_5.json.gz'
output_file = 'reviews_Cell_Phones_and_Accessories_5.json'

# Open the .gz file and write the uncompressed data to the output file
with gzip.open(input_file, 'rb') as f_in:
    with open(output_file, 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)


File decompressed successfully!


In [ ]:
# One line will be a whole json string
df = pd.read_json('reviews_Cell_Phones_and_Accessories_5.json', lines=True)

In [ ]:
df.head()

reviewerID        asin      reviewerName helpful  \
0  A30TL5EWN6DFXT  120401325X         christina  [0, 0]   
1   ASY55RVNIL0UD  120401325X          emily l.  [0, 0]   
2  A2TMXE2AFO7ONB  120401325X             Erica  [0, 0]   
3   AWJ0WZQYMYFQ4  120401325X                JM  [4, 4]   
4   ATX7CZYFXI1KW  120401325X  patrice m rogoza  [2, 3]   

                                          reviewText  overall  \
0  They look good and stick good! I just don't li...        4   
1  These stickers work like the review says they ...        5   
2  These are awesome and make my phone look so st...        5   
3  Item arrived in great time and was in perfect ...        4   
4  awesome! stays on, and looks great. can be use...        5   

                                     summary  unixReviewTime   reviewTime  
0                                 Looks Good      1400630400  05 21, 2014  
1                      Really great product.      1389657600  01 14, 2014  
2                             LOVE LOVE LOVE      1403740800  06 26, 2014  
3                                      Cute!      1382313600  10 21, 2013  
4  leopard home button sticker for iphone 4s      1359849600   02 3, 2013

In [ ]:
df.shape

(194439, 9)

#### Objective: Training a word2vec neural network using only the review 

In [ ]:
df.reviewText[0]

"They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up and it was irritating. I just won't buy a product like this again"

- Gensim has some utils that can be used to remove punctuations and making the text as lower and removing special characters etc ..

In [ ]:
gensim.utils.simple_preprocess(df.reviewText[0]) # Tokenizing the sample

['they',
 'look',
 'good',
 'and',
 'stick',
 'good',
 'just',
 'don',
 'like',
 'the',
 'rounded',
 'shape',
 'because',
 'was',
 'always',
 'bumping',
 'it',
 'and',
 'siri',
 'kept',
 'popping',
 'up',
 'and',
 'it',
 'was',
 'irritating',
 'just',
 'won',
 'buy',
 'product',
 'like',
 'this',
 'again']

In [ ]:
# Let's store the preprocessed text in a new column
review_text =  df.reviewText.apply(gensim.utils.simple_preprocess)

In [ ]:
review_text.head()

0    [they, look, good, and, stick, good, just, don...
1    [these, stickers, work, like, the, review, say...
2    [these, are, awesome, and, make, my, phone, lo...
3    [item, arrived, in, great, time, and, was, in,...
4    [awesome, stays, on, and, looks, great, can, b...
Name: reviewText, dtype: object

- What happens next, we utilize a window to walk over the text, it is called "Context Window"
- By this, we construct the training examples

In [ ]:
# The model implementation is done by word2vec
model = gensim.models.Word2Vec(
    window = 10, # it means 10 words before target words and 10 after
    min_count = 2, # ignore words that occur less than 2 times
    workers = 4, # use 4 cores
)

In [ ]:
model.build_vocab(review_text, progress_per=1000)

In [ ]:
model.epochs, model.corpus_count

(5, 194439)

In [ ]:
model.train(review_text,
            total_examples = model.corpus_count,
            epochs= model.epochs)

(61506818, 83868975)

In [ ]:
model.wv.most_similar("bad")

[('terrible', 0.6702101230621338),
 ('shabby', 0.6340645551681519),
 ('good', 0.5863435864448547),
 ('horrible', 0.5641374588012695),
 ('sad', 0.5379945039749146),
 ('awful', 0.5313628315925598),
 ('okay', 0.5283863544464111),
 ('ok', 0.5242146849632263),
 ('disappointing', 0.5126335024833679),
 ('poor', 0.5126115679740906)]

- Perfect, this is the similarity score! It means the model started to learn the language and know what words are related to each other

In [ ]:
model.wv.similarity(w1= "cheap", w2= "inexpensive")

0.5405482

In [ ]:
model.wv.similarity(w1= "great", w2 = "good")

0.78617793

### Assignment:

Download the following dataset and apply the pipeline of word2vec:
"http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Sports_and_Outdoors_5.json.gz"

In [ ]:
import gensim, pandas as pd, numpy as np
import gzip, shutil, os


In [ ]:
# File to decompress
input_file = ... # replace by your new input file
output_file = ... # replace by your new output file

# Open the .gz file and write the uncompressed data to the output file
with gzip.open(input_file, 'rb') as f_in:
    with open(output_file, 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)

> Read and analyze the data

#### Objective: Train a word2vec neural network using ...

In [ ]:
class Utility:
    
    @staticmethod    
    def load_data(file):
        df = ... # Continue
        print("Data shape is: ",df.shape)
        return ...
    
    @staticmethod
    def preprocessing(df):
        ... = ... # use simple_preprocess from gensim utils
        return ...
    
    @staticmethod
    def model_creation(window = 10,
                       min_count = 2,
                       workers = 4,
                       ):
        model = ...(    # Use Word2Vec from gensim models
            ...,
            ...,
            ...,
        )
        return model
    
    @staticmethod    
    def model_vocab(model, column, progress_per = 1000):
        ... # Use build vocab
        return model
    
    @staticmethod
    def train_model(model, column, epochs = model.epochs,
                    total_examples = model.corpus_count,):
        ... # Use train
    
    @staticmethod
    def model_evaluate_most_similar(model, word):
        print(...) # Use most_similar from model wv
    
    @staticmethod
    def model_evaluate_similarity(model, word1, word2):
        print(...) # Use similarity from model wv
    

In [ ]:
class Helper:
    @staticmethod
    def run_pipeline(word = "bad",
                     word1 = "great",
                     word2 = "good",
                     epochs = 5,
                     min_count = 2,
                     window = 10,
                     workers = 4):
        ... # Step1
        ... # Step2
        ... # Step3
        ... # Step4
        ... # Step5
        ... # Step6
        ... # Step7

In [ ]:
Helper.run_pipeline(...,
                    ...,
                    ...
                    ...,
                    ...,
                    ...,
                    ...
)